export enum Accesses {
    Home = 'خانه' as any,
    calender = 'تقویم' as any,
    User = 'کاربران' as any,
    UserType = 'پست ' as any,
    City = 'شهر' as any,
    Province = 'استان' as any,
    Currency = 'واحد پول' as any,
    Budget = 'بودجه' as any,
    WorkOrderRandom = 'آرشیو دستورکار تصادفی' as any,
    WorkOrderScheduling = ' آرشیو دستورکار زمانبندی شده' as any,
    WorkOrderStatus = 'وضعیت درخواست کار' as any,
    Measurement = 'واحد اندازه گیری' as any,
    Property = 'مشخصات ' as any,
    PropertyCategory = 'دسته بندی مشخصات' as any,
    Company = 'شرکت ' as any,
    // organization= <any>'سازمانها',
    Storage = 'انبار' as any,
    ChargeDepartment = 'دپارتمان مسئول' as any,
    assetCategory = ' خانواده گروه دارایی ' as any,
    AssetTemplate = 'قالب دارایی' as any,
    Asset = 'دارایی' as any,
    Project = 'مدیریت پروژه ' as any,
    Scheduling = 'زمانبندی نت' as any,
    TaskGroup = 'مدیریت مجموعه کار' as any,
    Part = 'قطعات' as any,
    Inventory = 'موجودی ' as any,
    AdjustInventory = 'تنظیم موجودی' as any,
    noticeBoard = 'کارتابل کاربری' as any,
    workRequest = 'ارسال درخواست تعمیر' as any,
    formCategory = 'دسته بندی فرم' as any,
    BOM = 'ساختار فنی ماشین آلات و تجهیزات' as any,
    formBuilder = 'مدیریت فرم ' as any,
    processBuilder = 'مدیریت فرآیند ' as any,
    metering = 'متراژ خوانی' as any,
    message = 'پیام رسانی' as any,
    AssignedAsset = 'دارایی تخصیص یافته' as any,
    AssignedPart = 'قطعات تخصیص یافته' as any,
    AssignedWorkOrder = 'دستور کار تخصیص یافته' as any,
    Report = 'گزارش گیری' as any,
    TypeOfActivity = 'نوع فعایت ' as any,
    WorkingField = 'رسته کاری ' as any,
    DegreeOfImportance = 'درجه اهمیت ' as any,
    Lubricant = 'روانکارها ' as any


}
